app_usuario:
    resource: "@AppBundle/Controller/UsuarioController.php"
    type:     annotation
    prefix: /Gestion

app:
    resource: '@AppBundle/Controller/ReporteController.php'
    type: annotation
    prefix: /Gestion

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

login:
    path:     /
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path:     /loginCheck
    defaults: { _controller: AppBundle:Security:loginCheck }

logout:
    path: /logout

mis_reportes:
    path: /misreportes
    defaults : { _controller: AppBundle:Usuario:misreportes }