# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\Usuario
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
        in_memory:
            memory: ~

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: reportes_pendientes

            logout:
                path: /logout
                target: login
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/Gestion/reporte/*, roles: [ROLE_ADMIN,ROLE_USUARIO] }
        - { path: ^/Gestion/usuario/change_password/*, roles: [ROLE_ADMIN,ROLE_USUARIO] }
        - { path: ^/Gestion/usuario, roles: [ROLE_ADMIN] }
